import ruDemo1 from '../data/examples/ru/demo-1.json'
import ruDemo2 from '../data/examples/ru/demo-2.json'
import ruDemo3 from '../data/examples/ru/demo-3.json'
import ruDemo4 from '../data/examples/ru/demo-4.json'
import ruDemo5 from '../data/examples/ru/demo-5.json'
import enDemo1 from '../data/examples/en/demo-1.json'
import enDemo2 from '../data/examples/en/demo-2.json'
import enDemo3 from '../data/examples/en/demo-3.json'
import enDemo4 from '../data/examples/en/demo-4.json'
import enDemo5 from '../data/examples/en/demo-5.json'
import plDemo1 from '../data/examples/pl/demo-1.json'
import plDemo2 from '../data/examples/pl/demo-2.json'
import plDemo3 from '../data/examples/pl/demo-3.json'
import plDemo4 from '../data/examples/pl/demo-4.json'
import plDemo5 from '../data/examples/pl/demo-5.json'
import type { FaceVariant, IconSetId, PaletteId } from '../types'
import { FACE_ORDER } from './accents'
import { knownIconSet } from './icons'
import { LANGS, type Lang } from './lang'
import { knownPalette } from './palettes'
import { normalizeTemplate } from './codec'
import { shortCode } from './shortcode'
import { publicSeasonHref } from './site'
import { normalizeFill } from './fill'
import type { FillState, Template } from './types'
import { EMPTY_FILL } from './types'

interface RawExample {
  name: string
  summary: string
  note: string
  palette: unknown
  icons?: unknown
  template: unknown
  fill: unknown
}

export interface Example {
  key: string
  id: string
  lang: Lang
  publicId: number
  href: string
  name: string
  summary: string
  note: string
  template: () => Template
  fill: FillState
  faces: FaceVariant[]
  palette: PaletteId
  iconSet: IconSetId
}

const RAW: Record<Lang, Record<string, RawExample>> = {
  ru: {
    'demo-1': ruDemo1,
    'demo-2': ruDemo2,
    'demo-3': ruDemo3,
    'demo-4': ruDemo4,
    'demo-5': ruDemo5,
  },
  en: {
    'demo-1': enDemo1,
    'demo-2': enDemo2,
    'demo-3': enDemo3,
    'demo-4': enDemo4,
    'demo-5': enDemo5,
  },
  pl: {
    'demo-1': plDemo1,
    'demo-2': plDemo2,
    'demo-3': plDemo3,
    'demo-4': plDemo4,
    'demo-5': plDemo5,
  },
}

// public_seasons.id is "generated BY DEFAULT as identity": a person's publication takes the next
// value from the sequence, an example is written with the id spelled out here, and an explicit id
// does not move the sequence. So the two share one range and are bound to meet - which is exactly
// what happened: the fourth example was given 10..12, the sequence had already handed 12 to a real
// publication, and the seed's "on conflict (id) do update" overwrote it, keeping its author.
//
// Hence the block from 1_000_001 for everything new. The first three examples keep 1..9: their
// codes have been handed out and a code is promised for ever. A short code is a permutation of
// thirty bits, so a million is nowhere near the ceiling.
export const SYSTEM_ID_BASE = 1_000_000

const PUBLIC_IDS: Record<Lang, Record<string, number>> = {
  ru: {
    'demo-1': 1,
    'demo-2': 2,
    'demo-3': 3,
    'demo-4': SYSTEM_ID_BASE + 1,
    'demo-5': SYSTEM_ID_BASE + 4,
  },
  en: {
    'demo-1': 4,
    'demo-2': 5,
    'demo-3': 6,
    'demo-4': SYSTEM_ID_BASE + 2,
    'demo-5': SYSTEM_ID_BASE + 5,
  },
  pl: {
    'demo-1': 7,
    'demo-2': 8,
    'demo-3': 9,
    'demo-4': SYSTEM_ID_BASE + 3,
    'demo-5': SYSTEM_ID_BASE + 6,
  },
}

export const DEFAULT_EXAMPLE_ID = 'demo-1'

export function exampleKey(lang: Lang, id: string): string {
  return `${lang}/${id}`
}

function facesOf(raw: RawExample): FaceVariant[] {
  const people = (raw.template as { people?: { face?: string }[] }).people ?? []
  return people
    .map((person) => person.face as FaceVariant)
    .filter((face) => FACE_ORDER.includes(face))
}

const EXAMPLES: Record<string, Example> = Object.fromEntries(
  LANGS.flatMap((lang) =>
    Object.entries(RAW[lang]).map(([id, raw]) => {
      const publicId = PUBLIC_IDS[lang][id]
      const key = exampleKey(lang, id)
      return [
        key,
        {
          key,
          id,
          lang,
          publicId,
          href: publicSeasonHref(lang, shortCode('public', publicId)),
          name: raw.name,
          summary: raw.summary,
          note: raw.note,
          template: () => normalizeTemplate(raw.template),
          fill: normalizeFill(raw.fill),
          faces: facesOf(raw),
          palette: knownPalette(raw.palette),
          iconSet: knownIconSet(raw.icons),
        } satisfies Example,
      ]
    }),
  ),
)

export function exampleByKey(key: string | null): Example | null {
  return (key && EXAMPLES[key]) ?? null
}

export function fillOf(key: string | null): FillState {
  return exampleByKey(key)?.fill ?? EMPTY_FILL
}

export const EXAMPLE_LIST: Example[] = Object.values(EXAMPLES)

export function examplesFor(lang: Lang): Example[] {
  return EXAMPLE_LIST.filter((example) => example.lang === lang)
}

export const LANDING_EXAMPLES = 3

// The landing shows one full row, not the whole collection: with five examples the fifth stood
// alone on a second line, and that only gets worse as examples are added. Three across, so the
// row is full at every width the cards are laid out at. They
// are picked at random rather than taken in order, so somebody who comes back is shown something
// else; that is the move the showcase already makes, and for the same reason. The landing itself
// therefore stops growing, and its caption stopped being a count.
export function landingExamples(lang: Lang): Example[] {
  const all = examplesFor(lang)
  if (all.length <= LANDING_EXAMPLES) return all

  const pool = [...all]
  for (let i = pool.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[pool[i], pool[j]] = [pool[j], pool[i]]
  }
  return pool.slice(0, LANDING_EXAMPLES)
}
