/* Built by tools/palettes/build.mjs (npm run palettes) from tools/palettes/source.json. */

export const PALETTES = [
  ['desert', { ru: 'Пустыня', en: 'Desert', pl: 'Pustynia' }],
  ['autumn', { ru: 'Осень', en: 'Autumn', pl: 'Jesień' }],
  ['foliage', { ru: 'Тёплая листва', en: 'Warm Foliage', pl: 'Ciepłe listowie' }],
  ['spice', { ru: 'Пряность', en: 'Spice', pl: 'Przyprawa' }],
  ['rustic', { ru: 'Тёплый рустик', en: 'Warm Rustic', pl: 'Ciepły rustykalny' }],
  ['jewel', { ru: 'Ювелирные тона', en: 'Jewel Tones', pl: 'Tony klejnotów' }],
  ['brownie', { ru: 'Шоколадный брауни', en: 'Chocolate Brownie', pl: 'Czekoladowe brownie' }],
  ['cozy', { ru: 'Уют и тепло', en: 'Cosy and Warm', pl: 'Ciepło i przytulnie' }],
  ['vineyard', { ru: 'Винный покой', en: 'Wine and Quiet', pl: 'Winny spokój' }],
  ['sunny-town', { ru: 'Солнечный городок', en: 'Sunny Town', pl: 'Słoneczne miasteczko' }],
  ['mediterranean', { ru: 'Средиземноморский полдень', en: 'Mediterranean Noon', pl: 'Śródziemnomorskie południe' }],
  ['autumn-orange', { ru: 'Осенний оранж', en: 'Autumn Orange', pl: 'Jesienny pomarańcz' }],
  ['golden-noon', { ru: 'Золотой полдень', en: 'Golden Noon', pl: 'Złote południe' }],
  ['scholar', { ru: 'Сила знаний', en: 'Power of Knowledge', pl: 'Siła wiedzy' }],
  ['warm-cool', { ru: 'Тёплая и стильная', en: 'Warm and Stylish', pl: 'Ciepła i stylowa' }],
  ['sea-wave', { ru: 'Морская волна', en: 'Sea Wave', pl: 'Morska fala' }],
  ['green-mist', { ru: 'Зелёный туман', en: 'Green Mist', pl: 'Zielona mgła' }],
  ['aqua', { ru: 'Водная синева', en: 'Water Blue', pl: 'Wodny błękit' }],
  ['city-fog', { ru: 'Туман мегаполиса', en: 'Metropolis Fog', pl: 'Mgła metropolii' }],
  ['arctic-dawn', { ru: 'Арктический рассвет', en: 'Arctic Dawn', pl: 'Arktyczny świt' }],
  ['ice', { ru: 'Голубые и серые льды', en: 'Blue and Grey Ice', pl: 'Błękitne i szare lody' }],
  ['iceland', { ru: 'Яркая Исландия', en: 'Bright Iceland', pl: 'Jasna Islandia' }],
  ['wet-forest', { ru: 'Лес после дождя', en: 'Forest After Rain', pl: 'Las po deszczu' }],
  ['modern', { ru: 'Современность', en: 'Modernity', pl: 'Nowoczesność' }],
  ['fresh-green', { ru: 'Свежая зелень', en: 'Fresh Greens', pl: 'Świeża zieleń' }],
  ['mountain-lake', { ru: 'Горное озеро', en: 'Mountain Lake', pl: 'Górskie jezioro' }],
  ['energy', { ru: 'Свежесть и энергия', en: 'Freshness and Energy', pl: 'Świeżość i energia' }],
  ['young-green', { ru: 'Молодая зелень', en: 'Young Green', pl: 'Młoda zieleń' }],
  ['green-fields', { ru: 'Зелёные поля', en: 'Green Fields', pl: 'Zielone pola' }],
  ['citrus-grass', { ru: 'Цитрус и трава', en: 'Citrus and Grass', pl: 'Cytrus i trawa' }],
  ['garden', { ru: 'Садовая свежесть', en: 'Garden Freshness', pl: 'Ogrodowa świeżość' }],
  ['fiesta', { ru: 'Летняя фиеста', en: 'Summer Fiesta', pl: 'Letnia fiesta' }],
  ['elegant-nature', { ru: 'Природная элегантность', en: 'Natural Elegance', pl: 'Naturalna elegancja' }],
  ['dusk', { ru: 'От заката до сумерек', en: 'Sunset to Dusk', pl: 'Od zachodu do zmierzchu' }],
  ['salmon-rye', { ru: 'Лосось и ржаной хлеб', en: 'Salmon and Rye', pl: 'Łosoś i żytni chleb' }],
  ['bird-view', { ru: 'С высоты полёта', en: 'From Above', pl: 'Z lotu ptaka' }],
  ['amber-azure', { ru: 'Янтарь и лазурь', en: 'Amber and Azure', pl: 'Bursztyn i lazur' }],
  ['neon-sign', { ru: 'Неоновая вывеска', en: 'Neon Sign', pl: 'Neonowy szyld' }],
  ['exotic', { ru: 'Экзотика и прочность', en: 'Exotic and Sturdy', pl: 'Egzotyka i trwałość' }],
  ['sun-sky', { ru: 'Солнце и небо', en: 'Sun and Sky', pl: 'Słońce i niebo' }],
  ['meadow', { ru: 'Цветочный луг', en: 'Flower Meadow', pl: 'Kwietna łąka' }],
  ['morning', { ru: 'Утренняя свежесть', en: 'Morning Freshness', pl: 'Poranna świeżość' }],
  ['tropic-flower', { ru: 'Тропический цветок', en: 'Tropical Flower', pl: 'Tropikalny kwiat' }],
  ['sunflower', { ru: 'Летний подсолнечник', en: 'Summer Sunflower', pl: 'Letni słonecznik' }],
  ['veggies', { ru: 'Корзинка овощей', en: 'Basket of Vegetables', pl: 'Koszyk warzyw' }],
  ['lemonade', { ru: 'Стойка с лимонадом', en: 'Lemonade Stand', pl: 'Stoisko z lemoniadą' }],
  ['tropic-fun', { ru: 'Весёлая и тропическая', en: 'Cheerful and Tropical', pl: 'Wesoła i tropikalna' }],
  ['figs-basil', { ru: 'Сыр, инжир и базилик', en: 'Cheese, Fig and Basil', pl: 'Ser, figa i bazylia' }],
  ['citrus-sun', { ru: 'Солнечный цитрус', en: 'Sunny Citrus', pl: 'Słoneczny cytrus' }],
  ['apple', { ru: 'Яблочный контраст', en: 'Apple Contrast', pl: 'Jabłkowy kontrast' }],
  ['neon-night', { ru: 'Неоновая ночь', en: 'Neon Night', pl: 'Neonowa noc' }],
  ['graffiti', { ru: 'Дерзость граффити', en: 'Graffiti Nerve', pl: 'Zuchwałość graffiti' }],
  ['nightlife', { ru: 'Ночная жизнь', en: 'Night Life', pl: 'Nocne życie' }],
  ['pool-party', { ru: 'Вечеринка с бассейном', en: 'Pool Party', pl: 'Impreza przy basenie' }],
  ['painting', { ru: 'Живопись', en: 'Painting', pl: 'Malarstwo' }],
  ['cappuccino', { ru: 'Чашка капучино', en: 'Cup of Cappuccino', pl: 'Filiżanka cappuccino' }],
  ['berry-blue', { ru: 'Ягодная синева', en: 'Berry Blue', pl: 'Jagodowy błękit' }],
  ['simple-chic', { ru: 'Изысканная простота', en: 'Refined Simplicity', pl: 'Wykwintna prostota' }],
  ['tech-nature', { ru: 'Технология и природа', en: 'Technology and Nature', pl: 'Technologia i natura' }],
  ['urban-life', { ru: 'Городская жизнь', en: 'City Life', pl: 'Miejskie życie' }],
  ['urban-oasis', { ru: 'Городской оазис', en: 'Urban Oasis', pl: 'Miejska oaza' }],
  ['modern-gloss', { ru: 'Современный лоск', en: 'Modern Polish', pl: 'Nowoczesny połysk' }],
  ['shabby-chic', { ru: 'Нейтральный шебби-шик', en: 'Neutral Shabby Chic', pl: 'Neutralny shabby chic' }],
  ['metallic', { ru: 'Классический металлик', en: 'Classic Metallic', pl: 'Klasyczny metalik' }],
  ['winter', { ru: 'Зимние краски', en: 'Winter Colours', pl: 'Zimowe barwy' }],
  ['sea-wheat', { ru: 'Море и пшеница', en: 'Sea and Wheat', pl: 'Morze i pszenica' }],
  ['offbeat', { ru: 'Самобытная и неожиданная', en: 'Distinct and Unexpected', pl: 'Odrębna i nieoczekiwana' }],
  ['cityscape', { ru: 'Городские виды', en: 'City Views', pl: 'Miejskie widoki' }],
  ['industrial', { ru: 'Индустриальная строгость', en: 'Industrial Rigour', pl: 'Industrialna surowość' }],
  ['authority', { ru: 'Профессионализм и власть', en: 'Professional and Powerful', pl: 'Profesjonalizm i władza' }],
  ['tulips', { ru: 'Нежные тюльпаны', en: 'Tender Tulips', pl: 'Delikatne tulipany' }],
  ['birds-berries', { ru: 'Птицы и ягоды', en: 'Birds and Berries', pl: 'Ptaki i jagody' }],
  ['retro', { ru: 'Стильное ретро', en: 'Stylish Retro', pl: 'Stylowe retro' }],
  ['barbecue', { ru: 'Летнее барбекю', en: 'Summer Barbecue', pl: 'Letni grill' }],
  ['spa', { ru: 'Безмятежность СПА', en: 'Spa Serenity', pl: 'Spokój SPA' }],
  ['pastel', { ru: 'Пастель', en: 'Pastel', pl: 'Pastele' }],
  ['strawberry', { ru: 'Клубника со сливками', en: 'Strawberries and Cream', pl: 'Truskawki ze śmietaną' }],
  ['antique', { ru: 'Приглушённая античность', en: 'Muted Antiquity', pl: 'Przygaszony antyk' }],
  ['metropolis', { ru: 'Мегаполис', en: 'Metropolis', pl: 'Metropolia' }],
  ['city-sun', { ru: 'Солнце в городе', en: 'Sun in the City', pl: 'Słońce w mieście' }],
  ['coast', { ru: 'Побережье', en: 'Coastline', pl: 'Wybrzeże' }],
  ['vintage', { ru: 'Винтаж', en: 'Vintage', pl: 'Vintage' }],
  ['easy-retro', { ru: 'Расслабляющее ретро', en: 'Relaxing Retro', pl: 'Relaksujące retro' }],
  ['refined', { ru: 'Утончённость', en: 'Refinement', pl: 'Wytworność' }],
  ['romance', { ru: 'Романтическая прогулка', en: 'Romantic Walk', pl: 'Romantyczny spacer' }],
  ['soft-contrast', { ru: 'Нежный контраст', en: 'Gentle Contrast', pl: 'Delikatny kontrast' }],
  ['school', { ru: 'Снова в школу', en: 'Back to School', pl: 'Znów do szkoły' }],
  ['smoky-purple', { ru: 'Дымчатый пурпур', en: 'Smoky Purple', pl: 'Dymny purpur' }],
  ['hygge', { ru: 'Хюгге', en: 'Hygge', pl: 'Hygge' }],
  ['day-night', { ru: 'День и ночь', en: 'Day and Night', pl: 'Dzień i noc' }],
  ['quiet-chic', { ru: 'Шик без вульгарности', en: 'Chic Without Vulgarity', pl: 'Szyk bez wulgarności' }],
  ['wild-berry', { ru: 'Ягоды земляники', en: 'Wild Strawberries', pl: 'Poziomki' }],
  ['bright-night', { ru: 'Яркая ночь', en: 'Bright Night', pl: 'Jasna noc' }],
  ['fifties', { ru: 'Кухня 1950-х', en: '1950s Kitchen', pl: 'Kuchnia lat 50.' }],
  ['city-contrast', { ru: 'Городские контрасты', en: 'Urban Contrasts', pl: 'Miejskie kontrasty' }],
  ['orange-accent', { ru: 'Оранжевый акцент', en: 'Orange Accent', pl: 'Pomarańczowy akcent' }],
  ['beyond-bw', { ru: 'По ту сторону чёрного и белого', en: 'Beyond Black and White', pl: 'Po drugiej stronie czerni i bieli' }],
  ['surf', { ru: 'Прибой у песчаного берега', en: 'Surf on Sandy Shore', pl: 'Fale na piaszczystym brzegu' }],
  ['greece', { ru: 'Греческие каникулы', en: 'Greek Holidays', pl: 'Greckie wakacje' }],
  ['sea-lights', { ru: 'Морские огни', en: 'Sea Lights', pl: 'Morskie światła' }],
] as const satisfies readonly (readonly [
  id: string,
  label: Readonly<Record<'ru' | 'en' | 'pl', string>>,
])[]
