-- Две породы сезонов, которые нельзя путать.

create table if not exists user_seasons (
  id           bigint      generated by default as identity primary key,
  code         text        not null unique,
  account_key  text        not null,
  title        text        not null,
  content      jsonb       not null,
  names        jsonb       not null,
  palette      text        not null,
  icon_set     text        not null,
  share_token  text        unique,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists user_seasons_owner on user_seasons (account_key, updated_at desc);

create table if not exists public_seasons (
  id            bigint      generated by default as identity primary key,
  code          text        not null unique,
  author_key    text,
  content       jsonb       not null,
  content_key   text        generated always as (md5(content::text)) stored unique,
  names         jsonb       not null,
  palette       text        not null,
  icon_set      text        not null,
  fill_id       text,
  rolling_month boolean     not null default false,
  hidden_at     timestamptz,
  created_at    timestamptz not null default now()
);

create index if not exists public_seasons_author on public_seasons (author_key, created_at desc);

create table if not exists public_favorites (
  account_key text        not null,
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (account_key, public_id)
);

create index if not exists public_favorites_season on public_favorites (public_id);

create table if not exists public_likes (
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  account_key text        not null,
  created_at  timestamptz not null default now(),
  primary key (public_id, account_key)
);

create table if not exists public_forks (
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  account_key text        not null,
  created_at  timestamptz not null default now(),
  primary key (public_id, account_key)
);

create table if not exists public_reports (
  id           bigint      generated by default as identity primary key,
  public_id    bigint      references public_seasons (id) on delete set null,
  code         text        not null,
  author_key   text,
  reporter_key text        not null,
  comment      text        not null,
  created_at   timestamptz not null default now()
);

create unique index if not exists public_reports_once on public_reports (public_id, reporter_key);

create index if not exists public_reports_author on public_reports (author_key, created_at desc);
