-- Две породы сезонов, которые нельзя путать.
--
--   user_seasons   — личные: своя коллекция, снаружи не видна, форк всегда даёт
--                    новую строку, содержимое правится сколько угодно.
--   public_seasons — публичные: выложенная идея, у которой есть постоянный
--                    короткий адрес, лайки, жалобы и избранное.
--
-- Публикация — **копия**, а не указатель на личный сезон: связи между таблицами
-- нет вовсе. Поэтому переименование или правка личного сезона на выложенное не
-- влияют, а удаление личного сезона публикацию не уносит.
--
-- В обеих лежит `content` — вывод `pack()` из `src/model/codec.ts`, то есть тот
-- же самый формат, что раньше уезжал в адресную строку. Второй копии состояния
-- по-прежнему нет: формат знает один `codec.ts`, а колонок «месяц», «тема» или
-- «люди» рядом не заводим — они вывелись бы из `content` и однажды разошлись.
--
-- Имена людей лежат **отдельно** от контента (`names`), и это не украшение:
-- по контенту считается уникальность публикации, а два одинаковых сезона с
-- разными именами — это один и тот же сезон. Оттуда же берётся обезличивание
-- при публикации: подменить надо ровно `names`.
--
-- Старые `seasons`, `favorites` и `shared_*` из `000_legacy.sql` пока живы:
-- сайт переезжает на новые таблицы по частям, и уронить его на первом же шаге
-- незачем. Уйдут они последним шагом переезда.

-- Личный сезон. Ни уникальности содержимого, ни уникальности названия здесь нет
-- и быть не должно: форк своего же сезона — это законная вторая строка.
create table if not exists user_seasons (
  -- Числовой id нужен ради кода: короткий адрес — перестановка его битов.
  id           bigint      generated by default as identity primary key,
  -- Постоянный короткий адрес (`/season/<code>`). Считается в приложении из id
  -- (`src/model/shortcode.ts`) и не меняется никогда: id не переиспользуются.
  code         text        not null unique,
  account_key  text        not null,
  -- Название даёт человек — при форке подставляется из текста и правится.
  title        text        not null,
  -- pack(template) с пустыми именами; сами имена — в `names`.
  content      jsonb       not null,
  -- ['Аня','Петя'] по порядку people. Именно массив, а не поле внутри контента.
  names        jsonb       not null,
  palette      text        not null,
  icon_set     text        not null,
  -- Приватная ссылка (`/p/<token>`): случайная, отзывается и выдаётся заново,
  -- поэтому не выводится из id, в отличие от `code`. null — не выдавалась.
  share_token  text        unique,
  created_at   timestamptz not null default now(),
  updated_at   timestamptz not null default now()
);

create index if not exists user_seasons_owner on user_seasons (account_key, updated_at desc);

-- Публичный сезон: выложенная идея. Автор — человек или сама система.
create table if not exists public_seasons (
  id            bigint      generated by default as identity primary key,
  -- Постоянный адрес `/s/<code>`. Тот же приём, что у личных, но свой ключ
  -- перестановки: коды двух таблиц не должны выглядеть родственными.
  code          text        not null unique,
  -- null — системный сезон (наши примеры). Всё остальное у него как у людских.
  author_key    text,
  content       jsonb       not null,
  -- Уникальность публикации: одинаковый контент выложить дважды нельзя.
  -- Считается базой, а не приложением, — так ключ не зависит от того, кто и чем
  -- его посчитал, а jsonb из одних массивов и скаляров печатается однозначно.
  -- Тема, набор рисунков и имена в ключ не входят намеренно: сезон, у которого
  -- поменяли краски, — тот же самый сезон.
  content_key   text        generated always as (md5(content::text)) stored unique,
  names         jsonb       not null,
  palette       text        not null,
  icon_set      text        not null,
  -- Набор заполнения (`src/data/examples/<id>.json`) — только у системных:
  -- «прожитый» сезон показывают примеры, у людских заполнения нет.
  fill_id       text,
  -- Системный пример обязан показывать текущий месяц, иначе он протухнет к
  -- следующему сентябрю. Месяц подставляется при чтении, а не хранится.
  rolling_month boolean     not null default false,
  -- Снят с витрины, но жив по прямой ссылке: так уходит сезон, который кто-то
  -- успел положить в избранное. Пусто — обычная видимая публикация.
  hidden_at     timestamptz,
  created_at    timestamptz not null default now()
);

create index if not exists public_seasons_author on public_seasons (author_key, created_at desc);

-- Избранное: единственное, что удерживает публикацию от настоящего удаления.
create table if not exists public_favorites (
  account_key text        not null,
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  created_at  timestamptz not null default now(),
  primary key (account_key, public_id)
);

-- «Сколько людей отложило этот сезон» — по этому индексу и считается.
create index if not exists public_favorites_season on public_favorites (public_id);

-- Лайк: строка на пару «публикация + аккаунт», счётчика рядом не держим.
-- Удалению публикации не мешает: лайк — знак внимания, а не чужая копия.
create table if not exists public_likes (
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  account_key text        not null,
  created_at  timestamptz not null default now(),
  primary key (public_id, account_key)
);

-- Форк: тоже только статистика. Форк — копия данных, а не ссылка на них,
-- поэтому удалению исходной публикации он не помеха.
create table if not exists public_forks (
  public_id   bigint      not null references public_seasons (id) on delete cascade,
  account_key text        not null,
  created_at  timestamptz not null default now(),
  primary key (public_id, account_key)
);

-- Жалоба живёт дольше публикации: она про **того, кто выложил**, а не только
-- про строку. Поэтому `public_id` обнуляется вместо каскада, а рядом остаются
-- код и автор — по ним разбираются, когда сезона уже нет.
create table if not exists public_reports (
  id           bigint      generated by default as identity primary key,
  public_id    bigint      references public_seasons (id) on delete set null,
  code         text        not null,
  author_key   text,
  reporter_key text        not null,
  comment      text        not null,
  created_at   timestamptz not null default now()
);

-- Одна жалоба на пару «публикация + жалобщик»: повторная уточняет прежнюю, а не
-- заводит вторую. На этом держится порог «шесть разных людей прячут сезон».
-- У жалоб на удалённые публикации `public_id` пуст, и они друг другу не мешают.
create unique index if not exists public_reports_once on public_reports (public_id, reporter_key);

create index if not exists public_reports_author on public_reports (author_key, created_at desc);
